drop table user_emails if exists;
drop table user_phone_numbers if exists;
drop table users if exists;
create table user_emails (user_id integer not null, email varchar(255), id integer);
create table user_phone_numbers (user_id integer not null, id integer, number varchar(255));
create table users (id integer generated by default as identity, first_name varchar(100) not null, last_name varchar(100) not null, primary key (id));
alter table user_emails add constraint FKgm8w4rt3pm1w70x97xa1dbkh2 foreign key (user_id) references users;
alter table user_phone_numbers add constraint FKeut9prmcgpertwb3vr2ik80bq foreign key (user_id) references users;